; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs =
	      secrets.ini
	      local.ini

[node32s]
platform = espressif32
framework = arduino
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
check_tool = clangtidy
monitor_filters = esp32_exception_decoder
build_type = release
extra_scripts = pre:build_svelte.py
lib_deps =
        chl33/og3@^0.5.0
        chl33/og3x-oled@^0.5.0
        chl33/og3x-shtc3@^0.5.0
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit SHTC3 Library@^1.0.0
	adafruit/Adafruit Unified Sensor@^1.1.0
	bakercp/CRC32
	bblanchon/ArduinoJson@^7.0.0
	elims/PsychicMqttClient@^0.2.4
	hoeken/PsychicHttp@^2.1.1
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	Wire
	SPI

build_flags =
	${local.build_flags}
	'-Wall'
	'-D OTA_PASSWORD="${secrets.otaPassword}"'
	'-D WIFI_OLED'
	'-D AP_PASSWORD="${secrets.apPassword}"'
lib_compat_mode = strict

[usb_node32s]
extends = node32s
upload_protocol = esptool
upload_port = /dev/ttyUSB0

[wifi_node32s]
extends = node32s
upload_protocol = espota
upload_flags =
        '${local.wifi_upload_flags}'
	--auth='${secrets.otaPassword}'
