; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs =
	      secrets.ini
	      secrets-usb.ini
;	      secrets-ota.ini

[env:node32s]
platform = espressif32
framework = arduino
board = esp32dev
board_build.filesystem = littlefs
monitor_speed = 115200
check_tool = clangtidy
monitor_filters = esp32_exception_decoder
build_type = release
extra_scripts = pre:build_svelte.py
lib_deps =
        ;watering
	symlink://../og3
	symlink://../og3x-oled
	symlink://../og3x-shtc3
#	chl33/og3@^0.4.3
#	og3x-oled@^0.3.1
#	og3x-shtc3@^0.3.0
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit SHTC3 Library@^1.0.0
	adafruit/Adafruit Unified Sensor@^1.1.0
	bakercp/CRC32
	bblanchon/ArduinoJson@^7.0.0
	elims/PsychicMqttClient@^0.2.4
	hoeken/PsychicHttp@^2.1.1
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	Wire
	SPI

build_flags =
	'-Wall'
	'-D OTA_PASSWORD="${secrets.otaPassword}"'
;	'-D LOG_DEBUG'
	'-D LOG_UDP'
	'-D WIFI_OLED'
	'-D LOG_UDP_ADDRESS=${secrets.udpLogTarget}'
	'-D AP_PASSWORD="${secrets.apPassword}"'
	'-D BOARD_V13=${hardware_options.boardV13}'

upload_protocol = ${secrets.uploadProtocol}
upload_port = ${secrets.uploadPort}
upload_flags =
	${secrets.uploadAuth}
	${secrets.uploadHostPort}
lib_ldf_mode = deep+
lib_compat_mode = strict
