name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Setup secrets for build
        run: cp secrets.ini.example secrets.ini && cp secrets-usb.ini.example secrets-usb.ini

      - name: Install svelteesp32
        run: npm install -D svelteesp32 build

      - name: Install svelteesp32
        run: npm install

      - name: Build svelte app
        run: npm run build

      - name: Package svelta app
        run: npx svelteesp32 -e async -s dist -o ../lib/watering/svelteesp32async.h --etag=true

      - name: Build PlatformIO Project
        run: pio run
